# runtime: nodejs8 # For Node.js 8, use runtime: nodejs8
#
# instance_class: F1
#
# handlers:
# - url: /favicon\.ico
#   static_files: src/favicon.ico
#   upload: src/favicon\.ico

runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html
- url: /
  static_dir: dist
- url: /favicon\.ico
  static_files: dist/favicon.ico
  upload: dist/favicon\.ico
